services:
  hexag:
    build: .
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "bun run generate && bun run migrate && bun run start"
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hexag
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
